### ISSUE TITLE
Update to Kotlin getter in Shard Config

### ISSUE THREAD

**Issue by leonkappes** [Votebot/bot#18]
Same as #15 but in Shard: 
https://github.com/Votebot/bot/blob/95aebab213e897b4762ae5c77be06a7760caa909/shard/src/main/kotlin/space/votebot/shard/config/Config.kt#L29

**Comment by DRSchlaubi** [comment]
Shall we update the title of #15 to `in ShardManager config` so it looks like it was planned to do it seperatly?

**Comment by yk-sgr** [comment]
That is a extraordinary, original and useful idea!
