### ISSUE TITLE
Use kotlin-logging instead of plain SLF4J

### ISSUE THREAD

**Issue by DRSchlaubi** [Votebot/bot#25]
I just found this cool library: https://github.com/MicroUtils/kotlin-logging
It would allow us to have a Kotlin based logger and it only creates the actual String object when the logging level is actually activated.
Should we try using it? It is compatible with SLF4J so it would not interfere with it

**Comment by yk-sgr** [comment]
no

**Comment by DRSchlaubi** [comment]
Reopening it since @ForYaSee agreed
https://rice.by.devs-from.asia/DiscordCanary_nhuGGLHBYl.png
